typography_spectrum: 0.85362
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.25
  lightness: 0.5625
  saturation: 0.25
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.25188
analytics:
  google: null
  facebook: null
  twitter: null
name: Benjamin Cunningham
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Benjamin Cunningham
purpose: []
