typography_spectrum: 0.5953061585314572
content_rating:
  adult: false
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.25
  lightness: 0.5625
  saturation: 0.25
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.04167943517677486
analytics:
  google: null
  facebook: null
  twitter: null
name: Benjamin Cunningham
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: About Me
    id: bb291640-5404-4a52-b9e2-0546d641ef9e
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/1be9d8f1-5491-4ce9-babc-3b50bf89f191.jpg
title: Writer & Journalist
description: ''
purpose: []
